// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Wakeup_screen_init(void)
{
    ui_Wakeup = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Wakeup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Wakeup, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Wakeup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Wakeup, &ui_img_bg3_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container7 = lv_obj_create(ui_Wakeup);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 240);
    lv_obj_set_height(ui_Container7, 132);
    lv_obj_set_align(ui_Container7, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wakeuptime1 = lv_spinbox_create(ui_Container7);
    lv_obj_set_width(ui_wakeuptime1, 100);
    lv_obj_set_height(ui_wakeuptime1, 60);
    lv_obj_set_x(ui_wakeuptime1, -50);
    lv_obj_set_y(ui_wakeuptime1, -20);
    lv_obj_set_align(ui_wakeuptime1, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_wakeuptime1, 4, 0);
    lv_spinbox_set_range(ui_wakeuptime1, 0, 9999);
    lv_spinbox_set_cursor_pos(ui_wakeuptime1, 1 - 1);
    lv_obj_set_style_text_font(ui_wakeuptime1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_decor(ui_wakeuptime1, LV_TEXT_DECOR_UNDERLINE, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wakeuptime1, &lv_font_montserrat_24, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_minus = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_minus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_minus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_minus, -30);
    lv_obj_set_y(ui_minus, 40);
    lv_obj_set_align(ui_minus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_minus, "-");
    lv_obj_add_flag(ui_minus, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_font(ui_minus, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_add = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_add, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_add, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_add, -80);
    lv_obj_set_y(ui_add, 40);
    lv_obj_set_align(ui_add, LV_ALIGN_CENTER);
    lv_label_set_text(ui_add, "+");
    lv_obj_add_flag(ui_add, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_font(ui_add, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wakeupSwitch = lv_switch_create(ui_Container7);
    lv_obj_set_width(ui_wakeupSwitch, 50);
    lv_obj_set_height(ui_wakeupSwitch, 25);
    lv_obj_set_x(ui_wakeupSwitch, 60);
    lv_obj_set_y(ui_wakeupSwitch, -20);
    lv_obj_set_align(ui_wakeupSwitch, LV_ALIGN_CENTER);

    ui_Image1 = lv_img_create(ui_Wakeup);
    lv_img_set_src(ui_Image1, &ui_img_icn_settings_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_Image1, -80);
    lv_obj_set_y(ui_Image1, 110);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container9 = lv_obj_create(ui_Wakeup);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, 112);
    lv_obj_set_height(ui_Container9, 29);
    lv_obj_set_x(ui_Container9, 120);
    lv_obj_set_y(ui_Container9, 280);
    lv_obj_set_align(ui_Container9, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Container9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container9, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel13 = lv_obj_create(ui_Container9);
    lv_obj_set_width(ui_Panel13, 10);
    lv_obj_set_height(ui_Panel13, 10);
    lv_obj_set_x(ui_Panel13, 5);
    lv_obj_set_y(ui_Panel13, 135);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel13, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Container9);
    lv_obj_set_width(ui_Panel1, 10);
    lv_obj_set_height(ui_Panel1, 10);
    lv_obj_set_x(ui_Panel1, 5);
    lv_obj_set_y(ui_Panel1, 135);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Container9);
    lv_obj_set_width(ui_Panel2, 10);
    lv_obj_set_height(ui_Panel2, 10);
    lv_obj_set_x(ui_Panel2, 5);
    lv_obj_set_y(ui_Panel2, 135);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_minus, ui_event_minus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_add, ui_event_add, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image1, ui_event_Image1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Wakeup, ui_event_Wakeup, LV_EVENT_ALL, NULL);

}
