// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Home
void ui_Home_screen_init(void);
void ui_event_Home(lv_event_t * e);
lv_obj_t * ui_Home;
lv_obj_t * ui_Container1;
lv_obj_t * ui_MinutePng;
lv_obj_t * ui_HourPng;
lv_obj_t * ui_secondPng;
lv_obj_t * ui_center1;
lv_obj_t * ui_center;
lv_obj_t * ui_Container2;
lv_obj_t * ui_weekday;
lv_obj_t * ui_date;
lv_obj_t * ui_TimeHour;
lv_obj_t * ui_TimeMinute;
lv_obj_t * ui_Container3;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_powerArc;
lv_obj_t * ui_powerImg;
lv_obj_t * ui_StepImg;
lv_obj_t * ui_stepCount;
// CUSTOM VARIABLES

// SCREEN: ui_Timer
void ui_Timer_screen_init(void);
void ui_event_Timer(lv_event_t * e);
lv_obj_t * ui_Timer;
lv_obj_t * ui_Container5;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_startbutton;
lv_obj_t * ui_Label5;
lv_obj_t * ui_stopbutton;
lv_obj_t * ui_Label1;
lv_obj_t * ui_clearbutton;
lv_obj_t * ui_Label2;
lv_obj_t * ui_timerhour;
lv_obj_t * ui_timerminute;
lv_obj_t * ui_timersecond;
// CUSTOM VARIABLES

// SCREEN: ui_SetTimePage
void ui_SetTimePage_screen_init(void);
void ui_event_SetTimePage(lv_event_t * e);
lv_obj_t * ui_SetTimePage;
lv_obj_t * ui_Container4;
lv_obj_t * ui_yearset;
lv_obj_t * ui_monthset;
lv_obj_t * ui_dayset;
lv_obj_t * ui_weekdayset;
lv_obj_t * ui_hourset;
lv_obj_t * ui_minset;
lv_obj_t * ui_Container6;
lv_obj_t * ui_Panel12;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_Panel10;
lv_obj_t * ui_startbutton2;
lv_obj_t * ui_Label4;
lv_obj_t * ui_yeartext;
lv_obj_t * ui_monthtext;
lv_obj_t * ui_daytext;
lv_obj_t * ui_weekdaytext;
lv_obj_t * ui_hourtext;
lv_obj_t * ui_minutetext;
// CUSTOM VARIABLES

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Container7;
lv_obj_t * ui_wakeuptime1;
void ui_event_minus(lv_event_t * e);
lv_obj_t * ui_minus;
void ui_event_add(lv_event_t * e);
lv_obj_t * ui_add;
lv_obj_t * ui_wakeupSwitch;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Home(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SetTimePage, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, &ui_SetTimePage_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Timer, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0, &ui_Timer_screen_init);
    }
}

void ui_event_Timer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, &ui_Home_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SetTimePage, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0, &ui_SetTimePage_screen_init);
    }
}

void ui_event_SetTimePage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Timer, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, &ui_Timer_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0, &ui_Home_screen_init);
    }
}

void ui_event_minus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_wakeuptime1, -1);
    }
}

void ui_event_add(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_wakeuptime1, 1);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Home_screen_init();
    ui_Timer_screen_init();
    ui_SetTimePage_screen_init();
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Home);
}
