// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Home
void ui_Home_screen_init(void);
void ui_event_Home(lv_event_t * e);
extern lv_obj_t * ui_Home;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_MinutePng;
extern lv_obj_t * ui_HourPng;
extern lv_obj_t * ui_secondPng;
extern lv_obj_t * ui_center1;
extern lv_obj_t * ui_center;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_weekday;
extern lv_obj_t * ui_date;
extern lv_obj_t * ui_TimeHour;
extern lv_obj_t * ui_TimeMinute;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_powerArc;
extern lv_obj_t * ui_powerImg;
extern lv_obj_t * ui_StepImg;
extern lv_obj_t * ui_stepCount;
// CUSTOM VARIABLES

// SCREEN: ui_Timer
void ui_Timer_screen_init(void);
void ui_event_Timer(lv_event_t * e);
extern lv_obj_t * ui_Timer;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_startbutton;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_stopbutton;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_clearbutton;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_timerhour;
extern lv_obj_t * ui_timerminute;
extern lv_obj_t * ui_timersecond;
// CUSTOM VARIABLES

// SCREEN: ui_SetTimePage
void ui_SetTimePage_screen_init(void);
void ui_event_SetTimePage(lv_event_t * e);
extern lv_obj_t * ui_SetTimePage;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_yearset;
extern lv_obj_t * ui_monthset;
extern lv_obj_t * ui_dayset;
extern lv_obj_t * ui_weekdayset;
extern lv_obj_t * ui_hourset;
extern lv_obj_t * ui_minset;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_startbutton2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_yeartext;
extern lv_obj_t * ui_monthtext;
extern lv_obj_t * ui_daytext;
extern lv_obj_t * ui_weekdaytext;
extern lv_obj_t * ui_hourtext;
extern lv_obj_t * ui_minutetext;
// CUSTOM VARIABLES

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_wakeuptime1;
void ui_event_minus(lv_event_t * e);
extern lv_obj_t * ui_minus;
void ui_event_add(lv_event_t * e);
extern lv_obj_t * ui_add;
extern lv_obj_t * ui_wakeupSwitch;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_bg2_png);    // assets/bg2.png
LV_IMG_DECLARE(ui_img_clockwise_min_png);    // assets/clockwise_min.png
LV_IMG_DECLARE(ui_img_clockwise_hour_png);    // assets/clockwise_hour.png
LV_IMG_DECLARE(ui_img_clock_sec_white_png);    // assets/clock_sec_white.png
LV_IMG_DECLARE(ui_img_flash_png);    // assets/flash.png
LV_IMG_DECLARE(ui_img_step_png);    // assets/step.png
LV_IMG_DECLARE(ui_img_bg3_png);    // assets/bg3.png

// FONTS
LV_FONT_DECLARE(ui_font_Size32);
LV_FONT_DECLARE(ui_font_Size45);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
