// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_SetTimePage_screen_init(void)
{
    ui_SetTimePage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SetTimePage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SetTimePage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetTimePage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SetTimePage, &ui_img_bg3_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_SetTimePage);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 240);
    lv_obj_set_height(ui_Container4, 320);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yearset = lv_dropdown_create(ui_Container4);
    lv_dropdown_set_options(ui_yearset, "\n2025\n2026\n2027");
    lv_obj_set_width(ui_yearset, 100);
    lv_obj_set_height(ui_yearset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_yearset, 60);
    lv_obj_set_y(ui_yearset, -130);
    lv_obj_set_align(ui_yearset, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yearset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_monthset = lv_dropdown_create(ui_Container4);
    lv_dropdown_set_options(ui_monthset, "\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n");
    lv_obj_set_width(ui_monthset, 100);
    lv_obj_set_height(ui_monthset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_monthset, 60);
    lv_obj_set_y(ui_monthset, -90);
    lv_obj_set_align(ui_monthset, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_monthset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_dayset = lv_dropdown_create(ui_Container4);
    lv_dropdown_set_options(ui_dayset,
                            "\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31");
    lv_obj_set_width(ui_dayset, 100);
    lv_obj_set_height(ui_dayset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dayset, 60);
    lv_obj_set_y(ui_dayset, -50);
    lv_obj_set_align(ui_dayset, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dayset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_weekdayset = lv_dropdown_create(ui_Container4);
    lv_dropdown_set_options(ui_weekdayset, "\nSUNDAY\nMONDAY\nTUESDAY\nWEDNESDAY\nTHURSDAY\nFRIDAY\nSATURDAY");
    lv_obj_set_width(ui_weekdayset, 100);
    lv_obj_set_height(ui_weekdayset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weekdayset, 60);
    lv_obj_set_y(ui_weekdayset, -10);
    lv_obj_set_align(ui_weekdayset, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weekdayset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_hourset = lv_dropdown_create(ui_Container4);
    lv_dropdown_set_options(ui_hourset,
                            "\n0\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23");
    lv_obj_set_width(ui_hourset, 100);
    lv_obj_set_height(ui_hourset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hourset, 60);
    lv_obj_set_y(ui_hourset, 30);
    lv_obj_set_align(ui_hourset, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hourset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_minset = lv_dropdown_create(ui_Container4);
    lv_dropdown_set_options(ui_minset,
                            "\n0\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59\n");
    lv_obj_set_width(ui_minset, 100);
    lv_obj_set_height(ui_minset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_minset, 60);
    lv_obj_set_y(ui_minset, 70);
    lv_obj_set_align(ui_minset, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_minset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Container6 = lv_obj_create(ui_SetTimePage);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 112);
    lv_obj_set_height(ui_Container6, 29);
    lv_obj_set_x(ui_Container6, 120);
    lv_obj_set_y(ui_Container6, 299);
    lv_obj_set_align(ui_Container6, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Container6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel12 = lv_obj_create(ui_Container6);
    lv_obj_set_width(ui_Panel12, 10);
    lv_obj_set_height(ui_Panel12, 10);
    lv_obj_set_x(ui_Panel12, 5);
    lv_obj_set_y(ui_Panel12, 135);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel12, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_Container6);
    lv_obj_set_width(ui_Panel8, 10);
    lv_obj_set_height(ui_Panel8, 10);
    lv_obj_set_x(ui_Panel8, 5);
    lv_obj_set_y(ui_Panel8, 135);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel8, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel10 = lv_obj_create(ui_Container6);
    lv_obj_set_width(ui_Panel10, 10);
    lv_obj_set_height(ui_Panel10, 10);
    lv_obj_set_x(ui_Panel10, 5);
    lv_obj_set_y(ui_Panel10, 135);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel10, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_startbutton2 = lv_btn_create(ui_SetTimePage);
    lv_obj_set_width(ui_startbutton2, 60);
    lv_obj_set_height(ui_startbutton2, 30);
    lv_obj_set_x(ui_startbutton2, -80);
    lv_obj_set_y(ui_startbutton2, 120);
    lv_obj_set_align(ui_startbutton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_startbutton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_startbutton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_startbutton2, lv_color_hex(0x8F8F8F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_startbutton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_startbutton2, 120, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_startbutton2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "SET");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_yeartext = lv_label_create(ui_SetTimePage);
    lv_obj_set_width(ui_yeartext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_yeartext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_yeartext, -60);
    lv_obj_set_y(ui_yeartext, -130);
    lv_obj_set_align(ui_yeartext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_yeartext, "YEAR");
    lv_obj_set_style_text_font(ui_yeartext, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_monthtext = lv_label_create(ui_SetTimePage);
    lv_obj_set_width(ui_monthtext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_monthtext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_monthtext, -60);
    lv_obj_set_y(ui_monthtext, -90);
    lv_obj_set_align(ui_monthtext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_monthtext, "MONTH");
    lv_obj_set_style_text_font(ui_monthtext, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_daytext = lv_label_create(ui_SetTimePage);
    lv_obj_set_width(ui_daytext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_daytext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_daytext, -60);
    lv_obj_set_y(ui_daytext, -50);
    lv_obj_set_align(ui_daytext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_daytext, "DAY");
    lv_obj_set_style_text_font(ui_daytext, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weekdaytext = lv_label_create(ui_SetTimePage);
    lv_obj_set_width(ui_weekdaytext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weekdaytext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weekdaytext, -60);
    lv_obj_set_y(ui_weekdaytext, -10);
    lv_obj_set_align(ui_weekdaytext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weekdaytext, "WEEKDAY");
    lv_obj_set_style_text_font(ui_weekdaytext, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hourtext = lv_label_create(ui_SetTimePage);
    lv_obj_set_width(ui_hourtext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hourtext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hourtext, -60);
    lv_obj_set_y(ui_hourtext, 30);
    lv_obj_set_align(ui_hourtext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hourtext, "HOUR");
    lv_obj_set_style_text_font(ui_hourtext, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minutetext = lv_label_create(ui_SetTimePage);
    lv_obj_set_width(ui_minutetext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_minutetext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_minutetext, -60);
    lv_obj_set_y(ui_minutetext, 70);
    lv_obj_set_align(ui_minutetext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_minutetext, "MINUTE");
    lv_obj_set_style_text_font(ui_minutetext, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SetTimePage, ui_event_SetTimePage, LV_EVENT_ALL, NULL);

}
