// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Screen1, &ui_img_bg3_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container7 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 240);
    lv_obj_set_height(ui_Container7, 68);
    lv_obj_set_align(ui_Container7, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wakeuptime1 = lv_spinbox_create(ui_Container7);
    lv_obj_set_width(ui_wakeuptime1, 80);
    lv_obj_set_height(ui_wakeuptime1, 40);
    lv_obj_set_x(ui_wakeuptime1, -50);
    lv_obj_set_y(ui_wakeuptime1, 0);
    lv_obj_set_align(ui_wakeuptime1, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_wakeuptime1, 4, 0);
    lv_spinbox_set_range(ui_wakeuptime1, 0, 9999);
    lv_spinbox_set_cursor_pos(ui_wakeuptime1, 1 - 1);
    lv_obj_set_style_text_font(ui_wakeuptime1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minus = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_minus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_minus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_minus, 10);
    lv_obj_set_y(ui_minus, 10);
    lv_obj_set_align(ui_minus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_minus, "-");
    lv_obj_add_flag(ui_minus, LV_OBJ_FLAG_CLICKABLE);     /// Flags

    ui_add = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_add, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_add, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_add, 10);
    lv_obj_set_y(ui_add, -10);
    lv_obj_set_align(ui_add, LV_ALIGN_CENTER);
    lv_label_set_text(ui_add, "+");
    lv_obj_add_flag(ui_add, LV_OBJ_FLAG_CLICKABLE);     /// Flags

    ui_wakeupSwitch = lv_switch_create(ui_Container7);
    lv_obj_set_width(ui_wakeupSwitch, 50);
    lv_obj_set_height(ui_wakeupSwitch, 25);
    lv_obj_set_x(ui_wakeupSwitch, 60);
    lv_obj_set_y(ui_wakeupSwitch, 0);
    lv_obj_set_align(ui_wakeupSwitch, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_minus, ui_event_minus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_add, ui_event_add, LV_EVENT_ALL, NULL);

}
